config/routes.rb
Rails.application.routes.draw do
  concern :searchable_by_name do
    collection do
      #get 'search(/:name)', action: :search, as: :search
      get 'search'
    end
  end
  resources :routes
  get 'welcome/index'
  resources :carriers, concerns: :searchable_by_name
  resources :stations, concerns: :searchable_by_name
  resources :cities, concerns: :searchable_by_name
  root "welcome#index"
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :city_start, class_name: "City"
  belongs_to :station_start, class_name: "Station"
  belongs_to :city_end, class_name: "City"
  belongs_to :station_end, class_name: "Station"
  belongs_to :carrier, optional: true
  enum currency: Rails.configuration.currency

  validates :currency, :inclusion => {in: Rails.configuration.currency}
  validates :cost, numericality: true

  attr_accessor :weeks_days
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /routes
  # GET /routes.json
  def index
    select_names = [:city_start, :city_end, :station_start, :station_end, :carrier]
    @q = Route.ransack(params[:q])
    @routes = @q.result.includes(select_names).page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:city_start_id, :station_start_id, :date_start, :city_end_id, :station_end_id, :date_end, :carrier_id, :cost, :currency)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= simple_form_for(@route) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :city_start %>
    <%= f.association :station_start %>
    <%= f.input :date_start %>
    <%= f.association :city_end %>
    <%= f.association :station_end %>
    <%= f.input :date_end %>
    <%= f.association :carrier %>
    <%= f.input :cost, as: :decimal %>
    <%= f.input :currency, as: :select, collection: Rails.configuration.currency.keys %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/routes/_search_form.html.erb
<%= search_form_for @q, remote: true, class: 'mb-4' do |f| %>

  <div class="form-group row">
    <%= f.label :city_start_id_eq, class: "col-lg-2 col-md-3 col-sm-4 col-form-label" %>
    <%= f.select :city_start_id_eq, [], {}, class: "form-control col-lg-4 col-md-5 col-sm-6" %>
  </div>

  <div class="form-group row">
    <%= f.label :station_start_id_eq, class: "col-lg-2 col-md-3 col-sm-4 col-form-label" %>
    <%= f.select :station_start_id_eq, [], {}, class: "form-control col-lg-4 col-md-5 col-sm-6" %>
  </div>

  <div class="form-group row">
    <%= f.label :city_end_id_eq, class: "col-lg-2 col-md-3 col-sm-4 col-form-label" %>
    <%= f.select :city_end_id_eq, [], {}, class: "form-control col-lg-4 col-md-5 col-sm-6" %>
  </div>

  <div class="form-group row">
    <%= f.label :station_end_id_eq, class: "col-lg-2 col-md-3 col-sm-4 col-form-label" %>
    <%= f.select :station_end_id_eq, [], {}, class: "form-control col-lg-4 col-md-5 col-sm-6" %>
  </div>

  <div class="form-group row">
    <%= f.label :carrier_id_eq, class: "col-lg-2 col-md-3 col-sm-4 col-form-label" %>
    <%= f.select :carrier_id_eq, [], {}, class: "form-control col-lg-4 col-md-5 col-sm-6" %>
  </div>

  <%= f.submit nil, class: "btn btn-primary" %>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<%= render 'search_form' %>

<div id='dynamic'>

  <table class="table">
    <thead>
      <tr>
        <th>City start - Station start</th>
        <th>Date start</th>
        <th>City end - Station end </th>
        <th>Date end</th>
        <th>Carrier</th>
        <th>Cost</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @routes.each do |route| %>
        <tr>
          <td><%= route.city_start %> (<%= route.city_start_id %>) <br /> <%= route.station_start %> (<%= route.station_start_id %>)</td>
          <td><%= l(route.date_start, format: :short) %></td>
          <td><%= route.city_end %> (<%= route.city_end_id %>) <br /> <%= route.station_end %> (<%= route.station_end_id %>)</td>
          <td><%= l(route.date_end, format: :short) %></td>
          <td><%= route.carrier %> (<%= route.carrier_id || "Не указан" %>)</td>
          <td><%= number_to_currency(route.cost, unit: route.currency, format: "%n %u" ) %></td>
          <td>
            <%= link_to 'Show', route %> <br>
            <%= link_to 'Edit', edit_route_path(route) %> <br>
            <%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @routes, remote: true %>

  <br>

  <%= link_to 'New Route', new_route_path %>

</div>

app/views/routes/index.js.erb
var wrapper = document.createElement('div');
wrapper.innerHTML = '<%= j(render template: 'routes/index.html.erb') %>';
document.querySelector('#dynamic').outerHTML = wrapper.querySelector('#dynamic').outerHTML;
window.scrollTo(0, 0);

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City start:</strong>
  <%= @route.city_start %>
</p>

<p>
  <strong>Station start:</strong>
  <%= @route.station_start %>
</p>

<p>
  <strong>Date start:</strong>
  <%= @route.date_start %>
</p>

<p>
  <strong>City end:</strong>
  <%= @route.city_end %>
</p>

<p>
  <strong>Station end:</strong>
  <%= @route.station_end %>
</p>

<p>
  <strong>Date end:</strong>
  <%= @route.date_end %>
</p>

<p>
  <strong>Carrier:</strong>
  <%= @route.carrier %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @route.cost %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @route.currency %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>