config/routes.rb
Rails.application.routes.draw do
  concern :searchable_by_name do
    collection do
      #get 'search(/:name)', action: :search, as: :search
      get 'search'
    end
  end
  resources :routes
  get 'welcome/index'
  resources :carriers, concerns: :searchable_by_name
  resources :stations, concerns: :searchable_by_name
  resources :cities, concerns: :searchable_by_name
  root "welcome#index"
end

app/views/layouts/admin.html.erb
<% content_for :content do %>

  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse mb-4">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Top navbar</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= current_page?(controller: "routes") ? "active" : "" %>">
          <%= link_to "Routes", routes_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= current_page?(controller: "cities") ? "active" : "" %>">
          <%= link_to "Cities", cities_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= current_page?(controller: "stations") ? "active" : "" %>">
          <%= link_to "Stations", stations_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= current_page?(controller: "carriers") ? "active" : "" %>">
          <%= link_to "Carriers", carriers_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "View my site", root_path, class: "btn btn-primary" %>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Busfor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>